# Main background
theme[main_bg]="#091321"

# Main text color
theme[main_fg]="#F5FAFF"

# Title color for boxes
theme[title]="#E8F2FC"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#F4A261"

# Background color of selected items
theme[selected_bg]="#233E5B"

# Foreground color of selected items
theme[selected_fg]="#7CCBFF"

# Color of inactive/disabled text
theme[inactive_fg]="#6F87A5"  

# Color of text appearing on top of graphs
theme[graph_text]="#DCE8F5"

# Misc colors for processes box
theme[proc_misc]="#DCE8F5"

# Cpu box outline color
theme[cpu_box]="#A2B8D0"

# Memory/disks box outline color
theme[mem_box]="#A2B8D0"

# Net up/down box outline color
theme[net_box]="#A2B8D0"

# Processes box outline color
theme[proc_box]="#A2B8D0"

# Box divider line and small boxes line color
theme[div_line]="#A2B8D0"

# Temperature graph colors
theme[temp_start]="#73D8EE"
theme[temp_mid]="#F4A261"
theme[temp_end]="#F4A261"

# CPU graph colors
theme[cpu_start]="#233E5B"
theme[cpu_mid]="#6CA8EF"
theme[cpu_end]="#7CCBFF"

# Mem/Disk free meter
theme[free_start]="#233E5B"
theme[free_mid]="#6CA8EF"
theme[free_end]="#7CCBFF"

# Mem/Disk cached meter
theme[cached_start]="#233E5B"
theme[cached_mid]="#6CA8EF"
theme[cached_end]="#7CCBFF"

# Mem/Disk available meter
theme[available_start]="#233E5B"
theme[available_mid]="#6CA8EF"
theme[available_end]="#7CCBFF"

# Mem/Disk used meter
theme[used_start]="#233E5B"
theme[used_mid]="#6CA8EF"
theme[used_end]="#7CCBFF"

# Download graph colors
theme[download_start]="#D4C3FF"
theme[download_mid]="#6CA8EF"
theme[download_end]="#233E5B"

# Upload graph colors
theme[upload_start]="#233E5B"
theme[upload_mid]="#ABE4CA"
theme[upload_end]="#8BC6AE"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#73D8EE"
theme[process_mid]="#EBCB8B"
theme[process_end]="#FFADB4"

