# primary
background = #091321
foreground = #DCE8F5
cursor-color = #7CCBFF
cursor-text = #000000

# normal colors
palette = 0=#172B43
palette = 1=#F07D86
palette = 2=#8BC6AE
palette = 3=#EBCB8B
palette = 4=#6CA8EF
palette = 5=#B5A0E6
palette = 6=#73D8EE
palette = 7=#E8F2FC

# bright colors
palette = 8=#6F87A5
palette = 9=#FFADB4
palette = 10=#ABE4CA
palette = 11=#FFE0A3
palette = 12=#A7D5FF
palette = 13=#D4C3FF
palette = 14=#A5F0FF
palette = 15=#F5FAFF
