## name :starship-quattro
foreground              #DCE8F5
background              #091321
selection_foreground    #091321
selection_background    #DCE8F5
cursor                  #7CCBFF
cursor_text_color       #000000
active_tab_foreground   #091321
active_tab_background   #DCE8F5
inactive_tab_foreground #DCE8F5
inactive_tab_background #091321

# black
color0  #172B43
color8  #6F87A5

# red
color1  #F07D86
color9  #FFADB4

# green
color2  #8BC6AE
color10 #ABE4CA

# yellow
color3  #EBCB8B
color11 #FFE0A3

# blue
color4  #6CA8EF
color12 #A7D5FF

# magenta
color5  #B5A0E6
color13 #D4C3FF

# cyan
color6  #73D8EE
color14 #A5F0FF

# white
color7  #E8F2FC
color15 #F5FAFF
